# Generated by Django 5.0.6 on 2024-05-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='vendor/')),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
