# Generated by Django 5.0.6 on 2024-05-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amt',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amt',
            field=models.FloatField(editable=False),
        ),
    ]
